### ISSUE TITLE
Warning in regards to Impersonation.

### ISSUE THREAD

**Issue by VillainsRule** [minesraft4/blooket-gui#27]
Hello,
We have evidence from Minesraft2 that this is a user of impersonation. Impersonation can end with jail time, and I doubt Minesraft2 wants to go there. Delete your Github account, or I am warning you, subpoenas may be issued to Github to collect data from your account. This isn't a threat, this is a **warning**. Minesraft has one way to contact him: his Discord at [discord.gg/kingdomofjod](https://discord.gg/kingdomofjod). The cheats are currently at [@VillainsRule/Blooket-Site](https://github.com/VillainsRule/Blooket-Site). Back off, your likely underage self shouldn't be on Github.
Thanks!
VillainsRule

**Comment by minesraft4** [comment]
I will talk with him soon also do read where it says that I don't want trouble.

**Comment by monkxy** [comment]
> I will talk with him soon also do read where it says that I don't want trouble.

"I don't want trouble" If you don't want trouble why would you impersonate someone and steal their work? It's a lot easier to delete the Github.

**Comment by monkxy** [comment]
Make sure you merge my pull request by the way I fixed some errors.

**Comment by DragonDude20** [comment]
Villain, do you know if Minesraft will be creating another account?

**Comment by DragonDude20** [comment]
Just wondereing

**Comment by VillainsRule** [comment]
> I will talk with him soon also do read where it says that I don't want trouble.

Minesraft is taking action. Trouble will come. Stop impersonating Minesraft2.

**Comment by VillainsRule** [comment]
> Villain, do you know if Minesraft will be creating another account?

Join discord.gg/kingdomofjod for info.

**Comment by monkxy** [comment]
Also

**Comment by monkxy** [comment]
May I ask why you lied and said Jod have you permission?

**Comment by monkxy** [comment]
![image](https://user-images.githubusercontent.com/113489420/228612725-27453d89-f323-4bff-ae3b-ced0a823ad6e.png)
Also looks like you're underaged but that's not important at this moment.

**Comment by 2C-P** [comment]
Because he can

**Comment by DeusOmmuim** [comment]
6 months later we got to get this guy down @VillainsRule

**Comment by VillainsRule** [comment]
it's an old issue lmao
